import { StyleSheet } from 'react-native';

import { screenBottomPadding } from '@/src/styles/layout';
import { colors, radius, shadow } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  containerDark: {
    backgroundColor: '#050505',
  },
  header: {
    paddingBottom: 14,
  },
  backButton: {
    alignSelf: 'flex-start',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  backButtonText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  kicker: {
    marginTop: 20,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  heading: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 6,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  actions: {
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 20,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    width: '100%',
  },
  importActionPressableFill: {
    flex: 1,
  },
  importActionButton: {
    minHeight: 46,
    maxHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  importActionButtonNeutral: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  importActionButtonNeutralDark: {
    borderColor: '#2a2a2a',
    backgroundColor: '#151515',
  },
  importActionButtonPrimary: {
    backgroundColor: colors.primary,
    ...shadow.soft,
  },
  importActionButtonFill: {
    flex: 1,
    width: '100%',
  },
  importActionButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  importActionButtonTextNeutral: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  importActionButtonTextPrimary: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '900',
  },
  primaryButton: {
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 11,
    ...shadow.soft,
  },
  disabledButton: {
    backgroundColor: colors.disabled,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '900',
  },
  list: {
    paddingTop: 0,
    paddingBottom: screenBottomPadding,
    gap: 12,
  },
  listItem: {
    marginHorizontal: 20,
  },
  summaryWrap: {
    marginHorizontal: 20,
    marginTop: 14,
  },
  summary: {
    gap: 10,
    marginBottom: 4,
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 16,
    ...shadow.card,
  },
  summaryCardDark: {
    borderColor: '#242424',
    backgroundColor: '#101010',
    shadowColor: '#000000',
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  summaryValue: {
    marginTop: 6,
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  summaryMeta: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  batchList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  batchChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  batchChipDark: {
    borderColor: '#242424',
    backgroundColor: '#080808',
  },
  batchChipActive: {
    borderColor: colors.primary,
    backgroundColor: '#fff1f2',
  },
  batchChipActiveDark: {
    borderColor: '#ffffff',
    backgroundColor: '#ffffff',
  },
  batchChipText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  batchChipTextActive: {
    color: colors.primary,
  },
  batchChipTextActiveDark: {
    color: '#050505',
  },
  card: {
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    ...shadow.card,
  },
  cardDark: {
    borderColor: '#242424',
    backgroundColor: '#101010',
    shadowColor: '#000000',
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    padding: 14,
    paddingBottom: 10,
  },
  poster: {
    width: 120,
    height: 180,
    borderRadius: radius.sm,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.ink,
    overflow: 'hidden',
  },
  posterImage: {
    height: '100%',
    width: '100%',
  },
  posterText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '900',
  },
  info: {
    flex: 1,
    minWidth: 0,
  },
  cardBody: {
    borderTopWidth: 1,
    borderTopColor: '#eef0f4',
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
  },
  cardBodyDark: {
    borderTopColor: '#242424',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 8,
  },
  title: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  badge: {
    flexShrink: 0,
    borderRadius: radius.sm,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  badgeSuggested: {
    backgroundColor: '#e0f2fe',
  },
  badgeDiscovered: {
    backgroundColor: '#f2f4f7',
  },
  badgeReview: {
    backgroundColor: '#fef3c7',
  },
  badgeApproved: {
    backgroundColor: '#dcfce7',
  },
  badgeRejected: {
    backgroundColor: '#fee2e2',
  },
  badgeText: {
    color: colors.ink,
    fontSize: 10,
    fontWeight: '900',
  },
  meta: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  genre: {
    marginTop: 5,
    color: colors.accent,
    fontSize: 13,
    fontWeight: '900',
  },
  warning: {
    marginTop: 7,
    color: '#92400e',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  description: {
    marginTop: 8,
    color: '#475467',
    fontSize: 13,
    lineHeight: 19,
  },
  descriptionDark: {
    color: '#c4cad4',
  },
  matchBox: {
    marginTop: 10,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    padding: 10,
  },
  matchBoxDark: {
    backgroundColor: '#171717',
  },
  matchLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  matchTitle: {
    marginTop: 3,
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 12,
  },
  secondaryButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  secondaryButtonDark: {
    borderColor: '#2a2a2a',
    backgroundColor: '#151515',
  },
  secondaryButtonText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  approveButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: radius.md,
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  approveButtonText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '900',
  },
  rejectButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: radius.md,
    backgroundColor: '#fef2f2',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  rejectButtonText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '900',
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
  centerDark: {
    backgroundColor: '#050505',
  },
  error: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: '800',
  },
  retryButton: {
    marginTop: 16,
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    color: colors.surface,
    fontWeight: '900',
  },
  empty: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    paddingVertical: 80,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '900',
  },
  emptyText: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
  },
  trailerBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(16, 24, 40, 0.72)',
    padding: 20,
  },
  trailerBackdropPressable: {
    ...StyleSheet.absoluteFill,
  },
  trailerModal: {
    width: '100%',
    maxWidth: 520,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    ...shadow.card,
  },
  trailerModalDark: {
    backgroundColor: '#101010',
    shadowColor: '#000000',
  },
  trailerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: 14,
  },
  trailerTitle: {
    flex: 1,
    color: colors.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  trailerCloseButton: {
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  trailerCloseText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  trailerPlayer: {
    backgroundColor: colors.ink,
  },
  textDark: {
    color: '#ffffff',
  },
  mutedTextDark: {
    color: '#a7b0c0',
  },
  accentTextDark: {
    color: '#8edbd2',
  },
});
