import { StyleSheet } from 'react-native';
import { bottomNavHeight } from '@/src/styles/layout';
import { colors, radius, shadow } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 20,
    paddingTop: 64,
    paddingBottom: bottomNavHeight + 24,
  },
  topActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 18,
  },
  backLink: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  backLinkText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '800',
  },
  historyButton: {
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  historyButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '900',
  },
  kicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  title: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 16,
    fontWeight: '800',
  },
  address: {
    marginTop: 8,
    color: '#475467',
    fontSize: 15,
    lineHeight: 22,
  },
  description: {
    marginTop: 12,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  sectionTitle: {
    marginTop: 30,
    marginBottom: 14,
    color: colors.ink,
    fontSize: 22,
    fontWeight: '900',
  },
  showtimeCard: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 12,
    ...shadow.card,
  },
  historyCard: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 12,
    ...shadow.soft,
  },
  poster: {
    width: 92,
    minHeight: 136,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    overflow: 'hidden',
  },
  posterText: {
    color: colors.surface,
    fontSize: 24,
    fontWeight: '900',
  },
  posterSmall: {
    width: 70,
    height: 98,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    overflow: 'hidden',
  },
  posterSmallText: {
    color: colors.surface,
    fontSize: 18,
    fontWeight: '900',
  },
  showtimeBody: {
    flex: 1,
  },
  movieTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  meta: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  genre: {
    alignSelf: 'flex-start',
    marginTop: 9,
    borderRadius: radius.sm,
    backgroundColor: '#fff3e0',
    color: '#9a3412',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: '900',
  },
  cardFooter: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 14,
  },
  price: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '900',
  },
  action: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: '900',
  },
  historyLabel: {
    borderRadius: radius.sm,
    backgroundColor: '#e5e7eb',
    color: colors.muted,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: '900',
  },
  empty: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 18,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '900',
  },
  emptyText: {
    marginTop: 6,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
  error: {
    color: colors.danger,
    fontSize: 16,
  },
  backButton: {
    marginTop: 16,
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  backButtonText: {
    color: colors.surface,
    fontWeight: '700',
  },
});
