import { StyleSheet } from 'react-native';
import { screenBottomPadding } from '@/src/styles/layout';
import { colors, radius, shadow } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  containerDark: {
    backgroundColor: '#050505',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 64,
    paddingBottom: 12,
  },
  backButton: {
    alignSelf: 'flex-start',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
    marginBottom: 18,
  },
  backButtonText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  kicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  heading: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 6,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  form: {
    marginHorizontal: 20,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 16,
    ...shadow.card,
  },
  formDark: {
    borderColor: '#242424',
    backgroundColor: '#101010',
    shadowColor: '#000000',
  },
  formTitle: {
    marginBottom: 12,
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  input: {
    minHeight: 48,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 13,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  inputDark: {
    borderColor: '#2a2a2a',
    backgroundColor: '#080808',
    color: '#ffffff',
  },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  toolbar: {
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  searchInput: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  list: {
    paddingTop: 0,
    paddingBottom: screenBottomPadding,
    gap: 12,
  },
  card: {
    flexDirection: 'row',
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    ...shadow.card,
  },
  cardDark: {
    borderColor: '#242424',
    backgroundColor: '#101010',
    shadowColor: '#000000',
  },
  image: {
    width: 112,
    minHeight: 128,
    backgroundColor: colors.ink,
  },
  info: {
    flex: 1,
    padding: 14,
  },
  name: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '900',
  },
  slug: {
    marginTop: 4,
    color: colors.accent,
    fontSize: 13,
    fontWeight: '900',
  },
  created: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  secondaryButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  secondaryButtonDark: {
    borderColor: '#2a2a2a',
    backgroundColor: '#151515',
  },
  secondaryButtonText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  submitButton: {
    minHeight: 38,
    minWidth: 86,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  submitButtonText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '900',
  },
  dangerButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: radius.md,
    backgroundColor: '#fef2f2',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  dangerButtonText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '900',
  },
  disabledButton: {
    backgroundColor: colors.disabled,
  },
  inlineError: {
    marginHorizontal: 20,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: radius.md,
    backgroundColor: '#fef2f2',
    padding: 12,
  },
  error: {
    color: colors.danger,
    fontSize: 14,
    fontWeight: '800',
  },
  empty: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    paddingVertical: 72,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '900',
  },
  emptyText: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
  textDark: {
    color: '#ffffff',
  },
  mutedTextDark: {
    color: '#a7b0c0',
  },
  accentTextDark: {
    color: '#8edbd2',
  },
});
