import { StyleSheet } from 'react-native';
import { colors, radius, shadow } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 20,
    paddingTop: 64,
    paddingBottom: 34,
  },
  topActions: {
    flexDirection: 'row',
    marginBottom: 18,
  },
  backButton: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  backButtonText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  kicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  heading: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  form: {
    marginTop: 22,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 18,
    ...shadow.card,
  },
  label: {
    marginBottom: 7,
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    minHeight: 50,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 13,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  textArea: {
    minHeight: 116,
    paddingTop: 12,
    paddingBottom: 12,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  rowField: {
    flex: 1,
  },
  genreHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 7,
  },
  manageGenresButton: {
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  manageGenresText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
  },
  emptyGenreText: {
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    padding: 12,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  genreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  genreOption: {
    width: '47%',
    minHeight: 84,
    borderWidth: 2,
    borderColor: 'transparent',
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    overflow: 'hidden',
  },
  genreOptionSelected: {
    borderColor: colors.primary,
  },
  genreImage: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    top: 0,
  },
  genreOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(16, 24, 40, 0.42)',
    padding: 10,
  },
  genreName: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '900',
  },
  posterPicker: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  posterPreview: {
    width: 96,
    height: 142,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    overflow: 'hidden',
  },
  posterImage: {
    height: '100%',
    width: '100%',
  },
  posterPlaceholder: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '900',
  },
  posterActions: {
    flex: 1,
    justifyContent: 'center',
    gap: 8,
  },
  posterButton: {
    alignSelf: 'flex-start',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  posterButtonText: {
    color: colors.surface,
    fontSize: 13,
    fontWeight: '900',
  },
  posterClearButton: {
    alignSelf: 'flex-start',
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  posterClearText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '900',
  },
  posterHint: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 2,
    marginBottom: 16,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    padding: 14,
  },
  switchText: {
    flex: 1,
  },
  switchTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  switchDescription: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  submitButton: {
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...shadow.soft,
  },
  submitButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  submitButtonText: {
    color: colors.surface,
    fontSize: 16,
    fontWeight: '900',
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
  error: {
    marginBottom: 14,
    color: colors.danger,
    fontSize: 14,
    fontWeight: '800',
  },
});
