import { StyleSheet } from 'react-native';
import { screenBottomPadding } from '@/src/styles/layout';
import { colors, radius, shadow } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  containerDark: {
    backgroundColor: '#050505',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 64,
    paddingBottom: 14,
  },
  headerText: {
    maxWidth: 520,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  backButton: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  backButtonText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  kicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  heading: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 6,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  toolbar: {
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
  },
  toolbarRow: {
    flexDirection: 'row',
    gap: 8,
    width: '100%',
  },
  searchInput: {
    flex: 1,
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  searchInputDark: {
    borderColor: '#2a2a2a',
    backgroundColor: '#080808',
    color: '#ffffff',
  },
  toolbarActionItem: {
    flex: 1,
  },
  toolbarPrimaryButton: {
    minHeight: 46,
    maxHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 11,
    ...shadow.soft,
  },
  toolbarPrimaryButtonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '900',
  },
  toolbarOutlineButton: {
    minHeight: 46,
    maxHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  toolbarOutlineButtonDark: {
    borderColor: '#2a2a2a',
    backgroundColor: '#151515',
  },
  toolbarOutlineButtonText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  list: {
    paddingTop: 0,
    paddingBottom: screenBottomPadding,
    gap: 12,
  },
  card: {
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    ...shadow.card,
  },
  cardDark: {
    borderColor: '#242424',
    backgroundColor: '#101010',
    shadowColor: '#000000',
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    padding: 14,
    paddingBottom: 10,
  },
  poster: {
    width: 120,
    height: 180,
    borderRadius: radius.sm,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.ink,
    overflow: 'hidden',
  },
  posterText: {
    color: colors.surface,
    fontSize: 22,
    fontWeight: '900',
  },
  info: {
    flex: 1,
    minWidth: 0,
  },
  cardBody: {
    borderTopWidth: 1,
    borderTopColor: '#eef0f4',
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
  },
  cardBodyDark: {
    borderTopColor: '#242424',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 10,
  },
  title: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  badge: {
    flexShrink: 0,
    borderRadius: radius.sm,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeActive: {
    backgroundColor: '#dcfce7',
  },
  badgeInactive: {
    backgroundColor: '#e5e7eb',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  badgeTextActive: {
    color: colors.success,
  },
  badgeTextInactive: {
    color: colors.muted,
  },
  meta: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  genre: {
    marginTop: 6,
    color: colors.accent,
    fontSize: 13,
    fontWeight: '900',
  },
  description: {
    marginTop: 8,
    color: '#475467',
    fontSize: 13,
    lineHeight: 19,
  },
  descriptionDark: {
    color: '#c4cad4',
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  secondaryButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  secondaryButtonDark: {
    borderColor: '#2a2a2a',
    backgroundColor: '#151515',
  },
  secondaryButtonText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  dangerButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#fecaca',
    borderRadius: radius.md,
    backgroundColor: '#fef2f2',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  dangerButtonText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '900',
  },
  restoreButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: radius.md,
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  restoreButtonText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '900',
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
  centerDark: {
    backgroundColor: '#050505',
  },
  error: {
    color: colors.danger,
    fontSize: 16,
    fontWeight: '800',
  },
  retryButton: {
    marginTop: 16,
    borderRadius: radius.md,
    backgroundColor: colors.ink,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    color: colors.surface,
    fontWeight: '900',
  },
  empty: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    paddingVertical: 80,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '900',
  },
  emptyText: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
  },
  textDark: {
    color: '#ffffff',
  },
  mutedTextDark: {
    color: '#a7b0c0',
  },
  accentTextDark: {
    color: '#8edbd2',
  },
});
