import { StyleSheet } from 'react-native';

import { bottomNavHeight } from '@/src/styles/layout';
import { colors, radius, shadow } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 20,
    paddingTop: 64,
    paddingBottom: bottomNavHeight + 24,
  },
  backButton: {
    alignSelf: 'flex-start',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
    marginBottom: 18,
  },
  backButtonText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  kicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  title: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  group: {
    marginTop: 22,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 16,
    ...shadow.card,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  sectionCount: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  optionList: {
    gap: 8,
  },
  optionRow: {
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  optionRowSelected: {
    borderColor: colors.primary,
    backgroundColor: '#fff1f2',
  },
  radioOuter: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 10,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  optionText: {
    flex: 1,
    minWidth: 0,
  },
  optionTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  optionMeta: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  roomChip: {
    minHeight: 42,
    maxWidth: '48%',
    minWidth: '31%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  roomChipSelected: {
    borderColor: colors.ink,
    backgroundColor: colors.ink,
  },
  roomChipText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  roomChipTextSelected: {
    color: colors.surface,
  },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 13,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  multilineInput: {
    minHeight: 92,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  movieList: {
    gap: 8,
    marginTop: 12,
  },
  movieRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  movieRowSelected: {
    borderColor: colors.primary,
    backgroundColor: '#fff1f2',
  },
  movieText: {
    flex: 1,
    minWidth: 0,
  },
  movieTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  movieMeta: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  selectedBadge: {
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
    color: colors.surface,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: '900',
  },
  selectedSummary: {
    maxWidth: 220,
    marginTop: 3,
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  switchText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  formGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  field: {
    flex: 1,
    minWidth: 150,
    marginBottom: 12,
  },
  priceField: {
    flex: 1,
    minWidth: 112,
    marginBottom: 12,
  },
  label: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 8,
  },
  primaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  buttonDisabled: {
    backgroundColor: colors.disabled,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: 15,
    fontWeight: '900',
  },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 10,
  },
  listTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '900',
  },
  listCount: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  showtimeList: {
    gap: 10,
  },
  showtimeCard: {
    minHeight: 68,
    alignItems: 'stretch',
    gap: 12,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 14,
    ...shadow.soft,
  },
  showtimeInfo: {
    flex: 1,
    minWidth: 0,
  },
  showtimeMovie: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  showtimeMeta: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  price: {
    width: '100%',
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
  },
  emptyPanel: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    padding: 16,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  emptyText: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  error: {
    marginTop: 14,
    color: colors.danger,
    fontSize: 14,
    fontWeight: '800',
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
});
