import { StyleSheet } from 'react-native';

import { bottomNavHeight } from '@/src/styles/layout';
import { colors, radius, shadow } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 20,
    paddingTop: 64,
    paddingBottom: bottomNavHeight + 24,
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  backButton: {
    alignSelf: 'flex-start',
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 9,
    marginBottom: 18,
  },
  backButtonText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  kicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  title: {
    marginTop: 4,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '900',
  },
  subtitle: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  panel: {
    marginTop: 22,
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 16,
    ...shadow.card,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  panelHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  panelTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '900',
  },
  panelMeta: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  formGrid: {
    gap: 12,
  },
  field: {
    gap: 8,
  },
  label: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 13,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  chipRail: {
    gap: 8,
    paddingRight: 6,
  },
  filterChip: {
    maxWidth: 190,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  filterChipSelected: {
    borderColor: colors.ink,
    backgroundColor: colors.ink,
  },
  filterChipText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  filterChipTextSelected: {
    color: colors.surface,
  },
  inlineLoader: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inlineLoaderText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
  },
  selectButton: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  selectButtonDisabled: {
    backgroundColor: '#f2f4f7',
    opacity: 0.8,
  },
  selectButtonText: {
    alignSelf: 'stretch',
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  selectPlaceholder: {
    color: '#98a2b3',
  },
  selectDisabledText: {
    color: colors.muted,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.48)',
    padding: 20,
  },
  selectModal: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 560,
    maxHeight: '82%',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 16,
    ...shadow.card,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  modalTitle: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  modalCloseButton: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  modalCloseText: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  optionList: {
    gap: 8,
    paddingTop: 12,
    paddingBottom: 4,
  },
  optionRow: {
    minHeight: 46,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  optionRowSelected: {
    borderColor: colors.ink,
    backgroundColor: colors.ink,
  },
  optionText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '800',
  },
  optionTextSelected: {
    color: colors.surface,
  },
  textArea: {
    minHeight: 88,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
  imagePicker: {
    alignItems: 'stretch',
    gap: 12,
  },
  imagePreview: {
    width: '100%',
    maxWidth: 560,
    aspectRatio: 16 / 9,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#f2f4f7',
  },
  imagePreviewMedia: {
    width: '100%',
    height: '100%',
  },
  imagePlaceholder: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '900',
  },
  imageActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 8,
  },
  hintText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  rowItem: {
    flex: 1,
    minWidth: 180,
  },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  primaryButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  dangerButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: '#fef3f2',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  restoreButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: '#ecfdf3',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  disabledButton: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: 14,
    fontWeight: '900',
  },
  secondaryButtonText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  dangerButtonText: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '900',
  },
  restoreButtonText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '900',
  },
  toggleRow: {
    gap: 8,
  },
  toggle: {
    alignSelf: 'flex-start',
    minHeight: 38,
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  toggleActive: {
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fdf4',
  },
  toggleInactive: {
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
  },
  toggleText: {
    fontSize: 13,
    fontWeight: '900',
  },
  toggleTextActive: {
    color: colors.success,
  },
  toggleTextInactive: {
    color: colors.danger,
  },
  list: {
    gap: 12,
  },
  cinemaCard: {
    borderWidth: 1,
    borderColor: '#e7eaf0',
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 14,
    ...shadow.soft,
  },
  cinemaCardSelected: {
    borderColor: colors.primary,
    backgroundColor: '#fff7f7',
  },
  cardTop: {
    gap: 12,
  },
  cinemaThumb: {
    width: '100%',
    aspectRatio: 16 / 9,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.ink,
  },
  cinemaThumbImage: {
    width: '100%',
    height: '100%',
  },
  avatar: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.ink,
  },
  avatarText: {
    color: colors.surface,
    fontSize: 24,
    fontWeight: '900',
  },
  cardInfo: {
    flex: 1,
    minWidth: 0,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  cardTitle: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  badge: {
    borderRadius: radius.sm,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeActive: {
    backgroundColor: '#dcfce7',
  },
  badgeInactive: {
    backgroundColor: '#fee4e2',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '900',
  },
  badgeTextActive: {
    color: colors.success,
  },
  badgeTextInactive: {
    color: colors.danger,
  },
  cardMeta: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  description: {
    marginTop: 10,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  selectedCinemaSummary: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    padding: 12,
    marginBottom: 14,
  },
  selectedCinemaTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  selectedCinemaMeta: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  roomEditor: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    padding: 12,
    marginBottom: 14,
  },
  roomCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: '#fbfcfe',
    padding: 12,
  },
  roomTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  roomName: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  emptyPanel: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    padding: 16,
  },
  emptyTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  emptyText: {
    marginTop: 5,
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  error: {
    marginTop: 14,
    color: colors.danger,
    fontSize: 14,
    fontWeight: '800',
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
});
